version: "3.9"
services:
  web:
    image: nergy101/catpouch:latest
    ports:
      - "8080:80"
    volumes:
      - .:/app
    links:
      - couchdb
    environment:
      - VITE_DB_URL
  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb/data:/opt/couchdb/etc/local.d
      - ./couchdb/local.ini:/opt/couchdb/etc/
      - ./couchdb/logs:/opt/couchdb/log/couch.log
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD

# env variables:
# - COUCHDB_USER
# - COUCHDB_PASSWORD
# - VITE_DB_URL

# docker-compose --env-file .env.dev up 
# docker-compose --env-file .env.prod.local up 