
name: Enable CouchDB cors

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Deploy to DigitalOcean"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        run: |
          HOST="http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@${COUCHDB_ADDRESS}" # or whatever you got
          curl -X GET $HOST/_membership
          curl -X PUT $HOST/_node/nonode@nohost/_config/httpd/enable_cors -d '"true"'
          curl -X PUT $HOST/_node/nonode@nohost/_config/cors/origins -d '"*"'
          curl -X PUT $HOST/_node/nonode@nohost/_config/cors/credentials -d '"true"'
          curl -X PUT $HOST/_node/nonode@nohost/_config/cors/methods -d '"GET, PUT, POST, HEAD, DELETE"'
          curl -X PUT $HOST/_node/nonode@nohost/_config/cors/headers -d '"accept, authorization, content-type, origin, referer, x-csrf-token"'